# Generated by Django 5.2.7 on 2025-12-13 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('users', '0002_alter_user_options_alter_user_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Payment date')),
                ('payment_amount', models.DecimalField(decimal_places=2, help_text='Enter payment amount', max_digits=10, verbose_name='Payment amount')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash payment'), ('transfer', 'Bank transfer')], help_text='Choose payment method', max_length=10, verbose_name='Payment method')),
                ('course', models.ForeignKey(blank=True, help_text='Enter course paid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.course', verbose_name='Course paid')),
                ('lesson', models.ForeignKey(blank=True, help_text='Enter lesson paid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.lesson', verbose_name='Lesson paid')),
                ('user', models.ForeignKey(help_text='Enter user email', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User email')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
