# Generated by Django 5.2.7 on 2025-12-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_payment_payment_url_payment_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Stripe price ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Stripe product ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Stripe session ID'),
        ),
    ]
