version: '3.9'  # Версия Docker Compose

services:
  web:
    build: .  # Указывает, что образ сервиса нужно собрать из Dockerfile в текущей директории
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16.0
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine

  celery:
    build: .
    command: celery -A config worker -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  beat:
    build: .
    command: celery -A config beat -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  static_volume:
