# Generated by Django 5.2.7 on 2025-10-07 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter course name', max_length=35, null=True, verbose_name='Course name')),
                ('preview', models.ImageField(blank=True, help_text='Upload course preview', null=True, upload_to='materials/courses/previews', verbose_name='Course preview')),
                ('description', models.CharField(blank=True, help_text='Enter course description', max_length=255, null=True, verbose_name='Course description')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter lesson name', max_length=35, null=True, verbose_name='Lesson name')),
                ('preview', models.ImageField(blank=True, help_text='Upload lesson preview', null=True, upload_to='materials/lessons/previews', verbose_name='Lesson preview')),
                ('description', models.CharField(blank=True, help_text='Enter lesson description', max_length=255, null=True, verbose_name='Lesson description')),
                ('video_link', models.URLField(blank=True, help_text='Enter video link', null=True, verbose_name='Video link')),
                ('course', models.ForeignKey(help_text='Choose course', null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.course', verbose_name='Course name')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
    ]
