# Generated by Django 5.2.7 on 2026-01-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_notification',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last update notification time'),
        ),
    ]
